"""create poi table

Revision ID: 3cacbe55e232
Revises: 
Create Date: 2026-04-27 12:44:20.820273

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cacbe55e232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('poi',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinates', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('tags_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('visit_duration_min', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('entrance_fee', sa.Float(), nullable=False),
    sa.Column('open_time', sa.Integer(), nullable=False),
    sa.Column('close_time', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_outdoor', sa.Boolean(), nullable=False),
    sa.Column('weather_penalty', sa.Float(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('datetime_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name', 'coordinates', name='uq_poi_name_coord'),
    sa.UniqueConstraint('uuid'),
    schema='travel'
    )
    op.create_geospatial_index('idx_poi_coordinates', 'poi', ['coordinates'], unique=False, schema='travel', postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_poi_price', 'poi', ['price'], unique=False, schema='travel')
    op.create_index('idx_poi_tags_vector', 'poi', ['tags_vector'], unique=False, schema='travel', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'tags_vector': 'vector_cosine_ops'})
    op.create_index('idx_poi_weather_penalty', 'poi', ['weather_penalty'], unique=False, schema='travel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_poi_weather_penalty', table_name='poi', schema='travel')
    op.drop_index('idx_poi_tags_vector', table_name='poi', schema='travel', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'tags_vector': 'vector_cosine_ops'})
    op.drop_index('idx_poi_price', table_name='poi', schema='travel')
    op.drop_geospatial_index('idx_poi_coordinates', table_name='poi', schema='travel', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('poi', schema='travel')
    # ### end Alembic commands ###
